'''Part 4: LLM-Based Cluster Analysis

Objective: Analyze clusters of semantically similar Twitter comments
using an LLM to extract structured insights about customer complaints 
and potential trends. 

Description: In this stage, each cluster of semantically similar comments
is analyzed using a Large Language Model (LLM). A structured prompt is designed
to provide the LLM with the grouped comments belonging to the same cluster and 
instruct it to analyze the underlying topic and customer issues.
The model returns a structured JSON output containing key analytical fields, which 
is then parsed and merged with the cleaned dataset, enriching it with structured insights
generated by the LLM. These features are later used in the next stage of the project to perform
trend analysis and identify patterns in customer feedback.
'''

# import libraries
import pandas as pd
import os
from dotenv import load_dotenv
from openai import OpenAI

# load env to read .env
load_dotenv()

# create client and read API key
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# open parquet
data = pd.read_parquet("tweets_clusters.parquet")

# create your prompt and define the model
def analyze_clusters(clusters): 
    prompt = f"""You are an expert airline customer experience analyst. 
    
    you will analyze a group of customer tweets that belong to the SAME cluster. 
    
    Your task is to generate structured business insights about the main customer pain point. 
    
    clusters: {clusters}
    
    - cluster_label: short name (max 2 words)
    - complaint_topic: one of ["delay","cancellation","baggage","service","fees","other","none"]
    - summary: max 10 words describing the pattern
    - customer_issue: max 5 words
    - likely_root_cause: max 5 words
    - severity: one of ["low","medium","high"]
    - is_complaint: boolean
    - trend_signal: one of ["low","medium","high"]

    Rules:
    - If the cluster is not about complaints, set complaint_topic to "none"
    - if a complain topic is highly recurrent within the cluster and it is not in the complaint_topic list, add the new recurrent topic to the complain_topic list. 
    - Base your answer ONLY on the provided tweets
    - Be concise and factual
    - Output only valid JSON
    """

    response = client.responses.create(
        model="gpt-4.1-mini",
        input = prompt
    )

    return response.output_text.strip().lower()

cluster_groups = (data.groupby("cluster")["text"]
                  .apply(list)
                  .to_dict()
                  )

def get_top_tweets(tweets, k=10):
    return tweets[:k]

cluster_insights = {}

for cluster_id, tweets in cluster_groups.items(): 
    top_tweets = get_top_tweets(tweets, k=10)
    
    insights = analyze_clusters(top_tweets)
    
    cluster_insights[cluster_id] = insights

cluster_df =(
    pd.DataFrame.from_dict(cluster_insights, orient="index")
    .reset_index()
    .rename(columns={"index": "cluster"})
)

df_enriched = data.merge(cluster_df, on="cluster", how="left")
print(df_enriched.shape)
print(df_enriched.isna().sum().sort_values(ascending=False).head())

output_path = r'.\tweets_enriched.parquet'

df_enriched.to_parquet(
    output_path,
    index=False,
    engine="pyarrow",
    compression="snappy"
)

